### ISSUE TITLE
Logo placement

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/components-on-a-grid#2]
@HannahDelaney

Everything is passed in Markbot, including the screenshot. However, the placement of the logo is bothering me and I just wanted to know as to how I could fix it?

**Comment by HannahDelaney** [comment]
It looks like you have your logo in `grid-row: 2`, but you'll want it to be part of the first grid row, correct? It's over the first, header, image. Then think about the vertical alignment within the row. You'll want it to be at the end...

You're missing a couple key elements but it should be a quick fix. If my covert hints aren't enough, search on here about vertical alignment: https://learn-the-web.algonquindesign.ca/topics/css-grid-cheat-sheet/#children

**Comment by Sophia-Villamayor** [comment]
@HannahDelaney Thank you for the help! For some reason, the cheat sheet page went missing

**Comment by HannahDelaney** [comment]
The link didn't work? That's super weird. Try this one: https://learn-the-web.algonquindesign.ca/topics/css-grid-cheat-sheet/
Otherwise, it's the one linked on this week's learn-the-web page.

**Comment by Sophia-Villamayor** [comment]
@HannahDelaney That one worked! Thank you!! I'll let you know if I encounter any struggle :)
